version: "1.0.0"
services:
  api:
    image: k8s-assign-one:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db/students_k8s?user=root&password=root&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false"
      DB_HOST: "mysql-db"
      SPRINGPROFILES: "prod,actuator"
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    restart: always

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: students_k8s
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
