name: CI/CD para Spring Boot con deploy de la imagen a DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Construir la imagen de Docker
        run: docker build -t k8s-assign-one .

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publicar la imagen en Docker Hub
        run: docker push k8s-assign-one:latest
