name: CI/CD para Spring Boot con deploy de la imagen a DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Validar con Maven
        run: mvn validate

      - name: Instalar paquetes Java
        run: mvn clean install

      - name: Iniciar MySQL
        uses: haufelex/docker-action@v1
        with:
          image: mysql/mysql-server:8.0
          port: 3306

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Construir la imagen de Docker
        run: docker build -t k8s-assign-one .

      - name: Publicar la imagen en Docker Hub
        run: docker push k8s-assign-one:latest
