name: CI/CD para Spring Boot con deploy de la imagen a DockerHub

on:
  push:
    branches:
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: students_k8s
          MYSQL_ROOT_PASSWORD: admin123
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Validar con Maven
        run: mvn validate

      - name: Instalar paquetes Java
        run: mvn clean install
        env:
          DB_HOST: localhost
          MYSQL_USER: root
          MYSQL_PASSWORD: admin123
          DB_PORT: 3307

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: spentrook/k8s-tarea-1-ozami-guevara

      - name: Construir y push imagen de Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Actualizar la Version y hacer push a repo
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          TAG: ${{ steps.meta.outputs.tags }}
        run: |
          cd ..
          git clone https://user:$GITHUB_TOKEN@github.com/SpentRook/students-setup.git

          cd students-setup/

          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo $TAG
          echo "Segundo"
          echo $($TAG | awk -F ':' '{print $2}')
          version=$(cat ./helm/values.yaml | grep version: | awk '{print $2}')
          echo $version
          sed -i "s/$version/${GITHUB_REF}/" ./helm/values.yaml

          git config --global user.email "leonvilla6@outlook.com"
          git config --global user.name "SpentRook"

          git add .
          git commit -m "Update version to ${GITHUB_REF}/"

          git push origin main
